x-common:
  &x-common
  build:
    context: ..
    dockerfile: dev/Dockerfile
    args:
      USERNAME: $USER
  volumes:
    - type: bind
      source: ../work
      target: /home/$USER/work
  init: true
  networks:
    argot_net:
  cap_add:
    - SYS_ADMIN
  devices:
    - /dev/fuse
  privileged: false
  command: >
    bash -c "sudo service ssh restart && sleep infinity"
  extra_hosts:
    - a1:172.30.3.2
    - a2:172.30.3.3
    - a3:172.30.3.4
    - a4:172.30.3.5

services:
  a1:
    <<: *x-common
    hostname: a1
    networks:
      argot_net:
        ipv4_address: 172.30.3.2
  a2:
    <<: *x-common
    hostname: a2
    networks:
      argot_net:
        ipv4_address: 172.30.3.3
  a3:
    <<: *x-common
    hostname: a3
    networks:
      argot_net:
        ipv4_address: 172.30.3.4
  a4:
    <<: *x-common
    hostname: a4
    networks:
      argot_net:
        ipv4_address: 172.30.3.5

networks:
  argot_net:
    name: argot_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.3.0/24
